title: "Gemigit" # title on the main page
database:
  type: "sqlite" # supported : sqlite(doesn't require cgo), sqlite3, mysql
  url: "gemigit.db" # connection string or sqlite3 database path

gemini:
  certificate: "cert.pem" # SSL certificate
  key: "key.pem" # private key
  address: "0.0.0.0" # address to listen on
  port: 1965 # bind port for gemini request
  templates: "./templates/" # templates directory
  #static: "./static" # serve a static directory (optional)

git:
  https: false # show https instead of http in the repository pages
  domain: "localhost" # domain for the http git request
  remote:
    enabled: false # read from a remote git server
    address: "https://git.example.com" # address to fetch repositories from
    key: "CHANGEME" # master key to send to the remote server
  address: "0.0.0.0" # address to listen on, disabled if remote is enabled
  port: 5555 # bind port for http git request, disabled if remote is enabled
  public: true # allow non-registered users to see public repositories
  #key: "CHANGEME" # master key having read/write access on all repositories

ldap:
  enabled: false # logging using ldap credential
  url: "ldaps://ldap.example.com" # url to the ldap server
  attribute: "cn" # attribute associated with the username
  binding: "ou=users,dc=example,dc=com"

users:
  registration: true # allow registration, will be disabled if ldap is enabled

protection:
  ip: 10 # Maximum connection attempts before the ip is blocked
  account: 30 # Maximum connection attempts before the account is blocked
  registration: 5 # Maximum number of registration per ip
  reset: 120 # Number of seconds before clearing the block on ip/accounts
